#!/usr/bin/env python3
"""
Windows Display Fix for Undetected Android Emulator

This script fixes UI display issues on Windows by modifying the QEMU configuration.
Run this script before starting the emulator to ensure proper display.
"""

import os
import sys
import logging
import platform

# Setup logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s [%(levelname)s] %(name)s: %(message)s',
    handlers=[
        logging.StreamHandler(),
        logging.FileHandler("display_fix.log")
    ]
)

logger = logging.getLogger("windows_display_fix")

def apply_display_fix():
    """Apply display configuration fixes for Windows."""
    if platform.system() != "Windows":
        logger.error("This script is only for Windows systems")
        print("ERROR: This fix is only for Windows systems")
        return False
    
    # Get configuration path
    config_dir = os.path.expanduser("~/.config/undetected-emulator")
    config_file = os.path.join(config_dir, "qemu.conf")
    
    # Create config directory if it doesn't exist
    os.makedirs(config_dir, exist_ok=True)
    
    # Default settings for the configuration
    config_settings = {
        "display": "sdl",
        "vga": "virtio",
        "audio": "none",
        "usbdevice": "tablet"
    }
    
    # Read existing config if available
    existing_config = {}
    if os.path.exists(config_file):
        try:
            with open(config_file, "r") as f:
                for line in f:
                    if "=" in line and not line.strip().startswith("#"):
                        key, value = line.strip().split("=", 1)
                        existing_config[key.strip()] = value.strip()
            
            # Save existing QEMU path
            if "qemu_path" in existing_config:
                config_settings["qemu_path"] = existing_config["qemu_path"]
        except Exception as e:
            logger.error(f"Error reading existing configuration: {e}")
    
    # Write updated configuration
    try:
        with open(config_file, "w") as f:
            f.write("# QEMU configuration for undetected Android emulator\n")
            f.write("# Generated by Windows display fix script\n\n")
            
            for key, value in config_settings.items():
                f.write(f"{key}={value}\n")
        
        logger.info(f"Updated configuration at {config_file}")
        return True
    except Exception as e:
        logger.error(f"Error writing configuration: {e}")
        return False

def main():
    """Main function."""
    print("Windows Display Fix for Undetected Android Emulator")
    print("--------------------------------------------------")
    
    if platform.system() != "Windows":
        print("This fix is only for Windows systems.")
        return 1
    
    print("Applying display configuration fixes...")
    
    if apply_display_fix():
        print("Display fix applied successfully!")
        print("\nYou can now run the emulator with improved display settings.")
        print("If you still experience issues, try using the run_emulator.bat file.")
        return 0
    else:
        print("ERROR: Failed to apply display fix.")
        print("Please check display_fix.log for details.")
        return 1

if __name__ == "__main__":
    try:
        sys.exit(main())
    except Exception as e:
        logger.exception(f"Unhandled exception: {e}")
        print(f"ERROR: {e}")
        print("Check display_fix.log for details")
        sys.exit(1)